#! /bin/sh
# =====================================
#  Tmux Setup Script
#
#  Checks and starts a session
#  splits window and starts vim.
# =====================================

# User input for session name.
name=$1

tmux start-server

tmux has-session -t ${name}


if [ "$?" != "0" ]; then
  tmux new-session -s ${name} -d -n Vim "vim" && \
  tmux split-window -t ${name} -p 20 && \
  tmux select-pane -t ${name}:1.2 && \
  tmux a -t ${name}
else
  tmux a -t ${name}
fi

