#! /bin/sh
# =====================================
#  Tmux Setup Script
#
#  Checks and starts a session
#  splits window and starts vim.
# =====================================

# User input for session name.
name=$1

# Set working directory.
dir="~/Development"

# Start tmux server.
tmux start-server

# Check if session exists.
tmux has-session -t ${name}

# If no session, create one.
if [ "$?" != "0" ]; then
  tmux new-session -s ${name} -n Vim -d

  tmux split-window -p 20 -t ${name}:1.1

  tmux send-keys -t ${name}:1.1 "cd ${dir}" C-m
  tmux send-keys -t ${name}:1.1 "vim" C-m

  tmux send-keys -t ${name}:1.2 "cd ${dir}" C-m
  tmux send-keys -t${name}:1.2 "l" C-m

  tmux new-window -n Files -t ${name}
  tmux send-keys -t ${name}:2 "cd ${dir}" C-m
  tmux send-keys -t${name}:2 "l" C-m

  tmux select-window -t ${name}:1
  tmux select-pane -U -t${name}

  tmux a -t ${name}
# Attach to existing session.
else
  tmux a -t ${name}
fi

